In [5]:
import numpy as np

In [7]:
x = np.random.randint(2,10,(3,3))

In [8]:
x

array([[2, 5, 3],
       [3, 8, 5],
       [2, 5, 3]])

In [13]:
np.insert(x,2,[[100],[200],[300]],axis=1)

array([[  2,   5, 100, 200, 300,   3],
       [  3,   8, 100, 200, 300,   5],
       [  2,   5, 100, 200, 300,   3]])

In [20]:
~np.ones((3,3),dtype = 'bool')

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
np.identity()