In [3]:
import numpy as np

In [12]:
np.identity(5)*3

array([[3., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.]])

In [9]:
np.eye(4,4, k = 3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
c = np.ones((4,4))
d = np.ones((4,4))


array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [21]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [24]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [25]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [27]:
print([[ a[i][j] for i in range(len(a))] for j in range(len(a[0]))])

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]
