In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])

In [8]:
id(a)

2947013602160

In [4]:
a[0] = 100

In [5]:
a

array([100,   2,   3,   4,   5,   6])

In [6]:
id(a)

2947013602160

In [9]:
np.array([10,'20'])

array(['10', '20'], dtype='<U11')

In [11]:
#int float complex str

In [17]:
np.array([10,'20',(20+3j)])

array(['10', '20', '(20+3j)'], dtype='<U64')

In [18]:
a.dtype

dtype('int32')

In [20]:
a.astype('float')

array([100.,   2.,   3.,   4.,   5.,   6.])

In [22]:
np.array([0,1,0,1]).astype('bool')

array([False,  True, False,  True])

In [25]:
np.array([1,3]) * [3]

array([3, 9])

In [33]:
np.ones((3,3))*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [32]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [34]:
np.full((2,3,3),100) 

array([[[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]]])

In [37]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [40]:
np.eye(4,5, k= 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
a


array([100,   2,   3,   4,   5,   6])

In [42]:
a.transpose()

array([100,   2,   3,   4,   5,   6])

In [50]:
a= np.array([[1,2,3],[4,5,6]])

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
print([[a[i][j] for i in range(len(a))] for j in range(len(a[0]))])

[[1, 4], [2, 5], [3, 6]]


In [58]:
a[0][0]

1

In [59]:
a[1][0]

4

In [64]:
a[0][1]

2

In [65]:
a[1][1]

5

In [66]:
a[0][2]

3

In [68]:
a[1][2]

6