In [1]:
import numpy as np

In [4]:
np.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [5]:
len(np.linspace(2,10))

50

In [16]:
np.linspace(2,10,num = 20,retstep = True, endpoint = False, dtype = 'int')

(array([2, 2, 2, 3, 3, 4, 4, 4, 5, 5, 6, 6, 6, 7, 7, 8, 8, 8, 9, 9]), 0.4)

In [17]:
np.linspace((2,3,2),10, num = 10, dtype = 'int')

array([[ 2,  3,  2],
       [ 2,  3,  2],
       [ 3,  4,  3],
       [ 4,  5,  4],
       [ 5,  6,  5],
       [ 6,  6,  6],
       [ 7,  7,  7],
       [ 8,  8,  8],
       [ 9,  9,  9],
       [10, 10, 10]])

In [24]:
a = np.linspace((3,4,6),10, num = 3, dtype = 'int')

In [25]:
a

array([[ 3,  4,  6],
       [ 6,  7,  8],
       [10, 10, 10]])

In [27]:

a.shape

(3, 3)

In [28]:
a.T

array([[ 3,  6, 10],
       [ 4,  7, 10],
       [ 6,  8, 10]])

In [29]:
a.transpose()

array([[ 3,  6, 10],
       [ 4,  7, 10],
       [ 6,  8, 10]])

In [30]:
np.transpose(a)

array([[ 3,  6, 10],
       [ 4,  7, 10],
       [ 6,  8, 10]])

In [40]:
a = np.linspace((2,3,5),9, num = 3, dtype = 'int',endpoint = False)

In [41]:
a

array([[2, 3, 5],
       [4, 5, 6],
       [6, 7, 7]])

In [42]:
a.T

array([[2, 4, 6],
       [3, 5, 7],
       [5, 6, 7]])

# random number

In [49]:
np.random.rand(2,2) # gives number from range 0 to 1 positive only

array([[0.07937513, 0.20291085],
       [0.77000244, 0.92123441]])

In [53]:
np.random.rand(3,3,3)

array([[[0.32364372, 0.0843019 , 0.26446942],
        [0.98694246, 0.78986649, 0.31667454],
        [0.02257165, 0.57630084, 0.75481757]],

       [[0.310827  , 0.89581764, 0.76353759],
        [0.94281978, 0.0721459 , 0.55572586],
        [0.94827561, 0.78744642, 0.15182381]],

       [[0.40526213, 0.46801879, 0.16218826],
        [0.87821468, 0.99932453, 0.98478003],
        [0.21112973, 0.01900662, 0.62187846]]])

In [78]:
a = np.random.randint(5, 15, size=(3, 3))

In [79]:
a

array([[12,  8,  5],
       [ 9, 12, 11],
       [ 8,  6,  8]])

In [89]:
np.random.randn(3,3) # it gives random output of both positive and negetive values

array([[-0.34917781, -1.14475061,  0.10689437],
       [ 0.05255618,  2.05338023,  1.16314382],
       [ 1.38560625, -0.04592887, -0.42546728]])

In [102]:
np.random.random((3,3))# it gives outpurt from 0.0 to 1.0 in float

array([[0.01489429, 0.80109676, 0.13432964],
       [0.83137775, 0.48471199, 0.12551774],
       [0.07518335, 0.80145049, 0.01548924]])

In [136]:
np.random.random_integers(2, 10,(3,3))

C:\Users\PRATIK~1\AppData\Local\Temp/ipykernel_7228/4164884896.py:1: DeprecationWarning: This function is deprecated. Please call randint(2, 10 + 1) instead
  np.random.random_integers(2, 10,(3,3))


array([[4, 2, 5],
       [4, 2, 4],
       [8, 9, 2]])

In [137]:


np.random.randint(2,10,(3,3))

array([[8, 5, 6],
       [8, 4, 3],
       [8, 6, 8]])

In [176]:
np.random.choice(3,(3,3))

array([[0, 1, 2],
       [0, 1, 0],
       [0, 1, 2]])

In [191]:
np.random.seed(2)
np.random.random(10)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
       0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728])

In [196]:
a = np.random.randint(1,8,(4,5))

In [197]:
a

array([[7, 1, 3, 6, 2],
       [2, 2, 7, 5, 3],
       [7, 4, 1, 4, 1],
       [3, 3, 1, 5, 7]])

In [198]:
a.shape

(4, 5)

In [201]:
a.reshape(2,10)

array([[7, 1, 3, 6, 2, 2, 2, 7, 5, 3],
       [7, 4, 1, 4, 1, 3, 3, 1, 5, 7]])

In [202]:
a

array([[7, 1, 3, 6, 2],
       [2, 2, 7, 5, 3],
       [7, 4, 1, 4, 1],
       [3, 3, 1, 5, 7]])

In [203]:
a.resize(5,4)

In [204]:
a

array([[7, 1, 3, 6],
       [2, 2, 2, 7],
       [5, 3, 7, 4],
       [1, 4, 1, 3],
       [3, 1, 5, 7]])

In [205]:
a

array([[7, 1, 3, 6],
       [2, 2, 2, 7],
       [5, 3, 7, 4],
       [1, 4, 1, 3],
       [3, 1, 5, 7]])

In [208]:
a.resize(2,10)

In [209]:
a

array([[7, 1, 3, 6, 2, 2, 2, 7, 5, 3],
       [7, 4, 1, 4, 1, 3, 3, 1, 5, 7]])